---
name: Pass the VAR

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/pass-the-var.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  envinput:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: envars
        env:
          FIRST_NAME: Ion
          LAST_NAME: Top
        with:
          result-encoding: string
          script: |
            const obj = Object.fromEntries(
              Object.entries(process.env)
              .filter(([key]) => ['FIRST_NAME', 'LAST_NAME'].includes(key))
            )
            console.log({obj})
            return JSON.stringify(obj)

      - name: Get result
        run: echo "${{steps.envars.outputs.result}}"

  envoutput:
    runs-on: ubuntu-latest
    steps:
      - name: Get result
        run: |
          echo "RAW: ${{ needs.envinput.envars.outputs.result }}"
          echo "fromJSON: ${{ fromJson(needs.envinput.envars.outputs.result) }}"
