---
name: Pass the VAR

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/pass-the-var.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  envars:
    runs-on: ubuntu-latest
    outputs:
      vars: ${{ steps.envars.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: envars
        env:
          FIRST_NAME: Ion
          LAST_NAME: Top
        with:
          result-encoding: string
          script: |
            const obj = Object.fromEntries(
              Object.entries(process.env)
              .filter(([key]) => ['FIRST_NAME', 'LAST_NAME'].includes(key))
            )
            console.log({obj})
            return JSON.stringify(obj)

      - name: Get result
        run: echo "${{steps.envars.outputs.result}}"

  output:
    runs-on: ubuntu-latest
    needs: envars
    steps:
      - name: Test env vars json output
        run: |
          echo "JSON: ${{ needs.envars.outputs.vars }}"

      - name: Set env vars from json
        uses: RaphaelNeumann/json-to-env-action@v1
        with:
          json_envs: ${{ needs.envars.outputs.vars }}

      - name: Test env vars
        run: echo "Hello, $FIRST_NAME $LAST_NAME"
